# fhish-cli/docker/Dockerfile.gateway
FROM node:20-alpine AS builder

WORKDIR /app
RUN apk add --no-cache git

# Clone dependencies
ARG CACHE_BUST=3
# Clone dependencies
RUN git clone https://github.com/fhish-tech/fhish-wasm.git /packages/fhish-wasm && \
    cd /packages/fhish-wasm && git checkout d0302083038700897d56cdd25c2f502dc2390b1c

# Build gateway
WORKDIR /app
RUN git clone https://github.com/fhish-tech/fhish-gateway.git . && \
    git checkout 35304d78d085949b2396abb4f5ca0c7ad2cf3192 && \
    npm install --no-audit --no-fund --legacy-peer-deps && \
    npm run build

FROM node:20-alpine
WORKDIR /app
COPY --from=builder /app ./
COPY --from=builder /packages /packages

# Ensure keys directories exist
RUN mkdir -p /app/keys /app/keys-shortint

ENTRYPOINT ["npm", "start"]
