FROM node:20-alpine

WORKDIR /app

# Copy WASM package
COPY packages/fhish-wasm/pkg-node /packages/fhish-wasm/pkg-node

# Install ethers and node-fetch (if needed)
RUN npm init -y && \
    npm install ethers@6

COPY fhish-cli/docker/scripts/verify-fhe.js /app/verify-fhe.js
COPY fhish-cli/docker/scripts/ct_yes.bin /app/ct_yes.bin
COPY fhish-cli/docker/scripts/ct_no.bin /app/ct_no.bin

ENTRYPOINT ["node", "/app/verify-fhe.js"]
