events {}

http {
    upstream minievm {
        server minievm:1317;
    }

    upstream rollytics {
        server rollytics-api:8080;
    }

    server {
        listen 1317;

        # Standard Initia Indexer API routing
        location /indexer/ {
            proxy_pass http://rollytics;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Standard Cosmos SDK API routing (LCD)
        location / {
            proxy_pass http://minievm;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
